# Generated by Django 4.1.5 on 2023-03-04 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=7)),
                ('clock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='main.clock')),
                ('decoration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='main.decoration')),
            ],
        ),
    ]
