# Generated by Django 4.1.5 on 2023-03-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subscriber_alter_clock_info_description_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
