# Generated by Django 4.1.5 on 2023-03-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='info_header_1',
            field=models.TextField(blank=True, null=True, verbose_name='Ինֆո 1 վերնագգիր '),
        ),
        migrations.AddField(
            model_name='clock',
            name='info_header_2',
            field=models.TextField(blank=True, null=True, verbose_name='Ինֆո 2 վերնագգիր '),
        ),
        migrations.AddField(
            model_name='clock',
            name='info_header_3',
            field=models.TextField(blank=True, null=True, verbose_name='Ինֆո 3 վերնագգիր'),
        ),
    ]
