# Generated by Django 4.1.5 on 2023-03-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
