# Generated by Django 4.1.5 on 2023-03-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clock',
            new_name='Product',
        ),
        migrations.RemoveField(
            model_name='wallclock',
            name='rubric',
        ),
        migrations.DeleteModel(
            name='Decoration',
        ),
        migrations.DeleteModel(
            name='WallClock',
        ),
    ]
