# Generated by Django 4.1.5 on 2023-03-08 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_clock_product_remove_wallclock_rubric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.rubric'),
        ),
    ]
