# Generated by Django 4.1.5 on 2023-03-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
