# Generated by Django 4.1.5 on 2023-03-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_color_clockcolor_clock_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='clock',
            name='info_description_1',
            field=models.TextField(verbose_name='Ինֆո 1 '),
        ),
        migrations.AlterField(
            model_name='clock',
            name='info_description_2',
            field=models.TextField(verbose_name='Ինֆո 2 '),
        ),
        migrations.AlterField(
            model_name='clock',
            name='info_description_3',
            field=models.TextField(verbose_name='Ինֆո 3 '),
        ),
        migrations.AlterField(
            model_name='clock',
            name='info_image_1',
            field=models.ImageField(upload_to='clock_photos/', verbose_name='Ինֆո 1 նկար'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='info_image_2',
            field=models.ImageField(upload_to='clock_photos/', verbose_name='Ինֆո 2 նկար'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='info_image_3',
            field=models.ImageField(upload_to='clock_photos/', verbose_name='Ինֆո 3 նկար'),
        ),
    ]
